### ISSUE TITLE
springmvc 传递日期参数给后台

### ISSUE THREAD

**Issue by mysterin** [mysterin/question_and_answer#3]
前提:
1. springmvc 框架中, 后台用一个实体类接收参数;
2. 实体类里面有个日期属性, 类型是 Date;
3. 前台是传递 yyyy-MM-dd HH:mm:ss 这样时间格式给后台;
4. springmvc 默认是不对日期参数转换, 所以接收参数是失败的.
代码如下:
```java
    @RequestMapping(value = "/update")
    @ResponseBody
    public Response update(AlertInfo alertInfo) {
        try {
            alertService.updateAlertInfo(alertInfo);
            return Response.build().success(true).code(0);
        } catch (IllegalAccessException e) {
            e.printStackTrace();
            return Response.build().success(false).code(1).msg("保存修改记录出错");
        }
    }
```
```java
public class AlertInfo {
    ...
    private Date flapStartWindow;
    ...
}
```
```java
Field error in object 'alertInfo' on field 'flapStartWindow': rejected value [2018-06-06 15:11:14]; codes [typeMismatch.alertInfo.flapStartWindow,typeMismatch.flapStartWindow,typeMismatch.java.util.Date,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [alertInfo.flapStartWindow,flapStartWindow]; arguments []; default message [flapStartWindow]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'flapStartWindow'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type java.util.Date for value '2018-06-06 15:11:14'; nested exception is java.lang.IllegalArgumentException]
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:112)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:79)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:157)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:124)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
```

**Comment by mysterin** [comment]
解决:
使用 @DateTimeFormat 对 Date 类型注解, 设置对应时间格式就可以转换参数了.
```java
public class AlertInfo {
    ...
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date flapStartWindow;
    ...
}
```
